/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.*;
import java.util.ArrayList;

public class JugadorPanel extends javax.swing.JPanel {
    private Jugador player;
    
    public void setJugador(Jugador newplayer){
        player = newplayer;
        if (player.isEncarcelado())
            texto_carcel.setText("Preso");
        else
            texto_carcel.setText("Libre");
        
        if ("JugadorEspeculador".equals(player.getClass().getName()))
            texto_especulador.setText("Lo es");
        else
            texto_especulador.setText("No lo es");
        
        texto_nombre.setText(player.getNombre());
        texto_saldo.setText(Float.toString(player.getSaldo()));
        
        rellenaPropiedades(player.getPropiedades());
        
        repaint();
        revalidate();
    }
    
    private void rellenaPropiedades(ArrayList<TituloPropiedad> lista){
        
        this.propiedades.removeAll();
        for (TituloPropiedad t : lista){
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            
            this.propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        repaint();
        revalidate();
    }
    
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_nombre = new javax.swing.JLabel();
        Label_saldo = new javax.swing.JLabel();
        Label_encarcelado = new javax.swing.JLabel();
        Label_especulador = new javax.swing.JLabel();
        texto_carcel = new javax.swing.JTextField();
        texto_especulador = new javax.swing.JTextField();
        texto_saldo = new javax.swing.JTextField();
        texto_nombre = new javax.swing.JTextField();
        propiedades = new javax.swing.JPanel();

        Label_nombre.setText("Nombre");
        Label_nombre.setEnabled(false);

        Label_saldo.setText("Saldo");
        Label_saldo.setEnabled(false);

        Label_encarcelado.setText("Estado Carcel");
        Label_encarcelado.setEnabled(false);

        Label_especulador.setText("Especulador");
        Label_especulador.setEnabled(false);

        texto_carcel.setText("jTextField1");
        texto_carcel.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        texto_carcel.setEnabled(false);

        texto_especulador.setText("jTextField2");
        texto_especulador.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        texto_especulador.setEnabled(false);

        texto_saldo.setText("jTextField3");
        texto_saldo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        texto_saldo.setEnabled(false);

        texto_nombre.setText("jTextField4");
        texto_nombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        texto_nombre.setEnabled(false);

        javax.swing.GroupLayout propiedadesLayout = new javax.swing.GroupLayout(propiedades);
        propiedades.setLayout(propiedadesLayout);
        propiedadesLayout.setHorizontalGroup(
            propiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );
        propiedadesLayout.setVerticalGroup(
            propiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_encarcelado)
                    .addComponent(Label_especulador)
                    .addComponent(Label_saldo)
                    .addComponent(Label_nombre))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto_especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_carcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_nombre)
                            .addComponent(texto_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_saldo)
                            .addComponent(texto_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_encarcelado)
                            .addComponent(texto_carcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_especulador)
                            .addComponent(texto_especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 111, Short.MAX_VALUE))
                    .addComponent(propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_encarcelado;
    private javax.swing.JLabel Label_especulador;
    private javax.swing.JLabel Label_nombre;
    private javax.swing.JLabel Label_saldo;
    private javax.swing.JPanel propiedades;
    private javax.swing.JTextField texto_carcel;
    private javax.swing.JTextField texto_especulador;
    private javax.swing.JTextField texto_nombre;
    private javax.swing.JTextField texto_saldo;
    // End of variables declaration//GEN-END:variables
}
